name: Update

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: Update
    uses: hasundue/actions/.github/workflows/update-deno.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.PAT_UPDATE }}
